/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package attendance;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Prem
 */
public class do_attendance extends javax.swing.JFrame {
Connection conn=null;
    PreparedStatement pst=null;
ResultSet rs=null;
    /**
     * Creates new form do_attendance
     */
    public do_attendance() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtsemester = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblstudent = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        txtdate = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtsubmit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtstatus = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txtsemester.setFont(new java.awt.Font("Tempus Sans ITC", 2, 24)); // NOI18N
        txtsemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        txtsemester.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtsemesterItemStateChanged(evt);
            }
        });
        txtsemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsemesterActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 2, 24)); // NOI18N
        jLabel5.setText("Semester");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtsemester, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        tblstudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblstudent.getTableHeader().setReorderingAllowed(false);
        tblstudent.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                tblstudentComponentAdded(evt);
            }
        });
        jScrollPane1.setViewportView(tblstudent);

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 2, 24)); // NOI18N
        jLabel3.setText("TODAY");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        txtsubmit.setText("Submit");
        txtsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubmitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 2, 24)); // NOI18N
        jLabel1.setText("Status");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/phpuXftfuAM.jpg"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel9)
                        .addGap(72, 72, 72)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtsubmit)))
                .addContainerGap(243, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)))
                .addGap(36, 36, 36)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtsubmit)
                        .addComponent(txtstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm");
Date date = new Date();
txtdate.setText(dateFormat.format(date));
 DefaultTableModel t = (DefaultTableModel) tblstudent.getModel();
String sem=(String) txtsemester.getSelectedItem();
        t.addColumn("ID");
        t.addColumn("Name");
        t.addColumn("Roll No.");
        t.addColumn("Status P/A");
       
// ORDER BY id DESC LIMIT 0 , 10
        MySQLConnect.connectDb();
        try {
            String sql = "SELECT * FROM  `student` WHERE `Semester` = '"+sem+"'";
            pst = MySQLConnect.conn.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {
                t.addRow(new Object[]{
                    rs.getString("ID"),
                    rs.getString("Name"),
                    rs.getString("Roll_no"),
                    rs.getString("Status"),
                     
//rs.getString(""),
                    
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

                                 // TODO add your handling code here:
    


    

                                 // TODO add your handling code here:
    

            // TODO add your handling code here:
                                           

// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened
/**/
    private void txtsemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsemesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsemesterActionPerformed

    private void txtsemesterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtsemesterItemStateChanged
        DefaultTableModel t=(DefaultTableModel) tblstudent.getModel();
        String select=(String) txtsemester.getSelectedItem();
        t.setRowCount(0);
        String sql = "SELECT DISTINCT(ID), name, Roll_no, Status FROM `student` WHERE `Semester` = '"+select+"'";
        System.out.println(sql);
        try {
            pst=MySQLConnect.conn.prepareStatement(sql);
            rs=pst.executeQuery();
            while (rs.next()) {
                t.addRow(new Object[]{
                    rs.getString("ID"),
                    rs.getString("Name"),
                    rs.getString("Roll_no"),
                    //ADD BUTTON TO FORM
   // rs.setBounds(20,30,130,30);
    //getContentPane().add(rs);

                });
            }

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

        // TODO add your handling code here:

        // TODO add your handling code here:
    }//GEN-LAST:event_txtsemesterItemStateChanged

    private void tblstudentComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_tblstudentComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tblstudentComponentAdded

    private void txtsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubmitActionPerformed
 String status=txtstatus.getText();
// button update selected row
      
DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
String cdate=dateFormat.format(new Date());
      
DefaultTableModel t=(DefaultTableModel)tblstudent.getModel();
       int a=tblstudent.getSelectedRowCount();
if(a!=1){
    JOptionPane.showMessageDialog(null,"Select a row");
}
else
        {
            String id=tblstudent.getValueAt(tblstudent.getSelectedRow(),0).toString();
            System.out.println("Updating User....ID!"+id);
     try{       
         MySQLConnect.connectDb();
        String sql = "UPDATE `student` SET `Status`='"+status+"', `Date`='"+cdate+"' WHERE `ID`='" +id+"'";
     
         pst = MySQLConnect.conn.prepareStatement(sql);
     
        int b = pst.executeUpdate();
        if (b != 0) {
            JOptionPane.showMessageDialog(null, "Success");
            do_attendance h = new do_attendance();
                h.setVisible(true);
                this.dispose();
        }}
        catch (HeadlessException | SQLException e) {
        System.out.println(e.getMessage());
                  
        
     }
        }
         /*   UserUpdateForm u=new UserUpdateForm();
            u.setVisible(true);
            u.setTitle("Update User#"+id);
            u.txtlabel1.setText("Update User#"+id);
            //u.setVisible(true);
            this.dispose();
        }


          
      /* try {
        MySQLConnect.connectDb();
        String sql = "UPDATE `student` SET `Status`='"+status +"' WHERE `ID`='" + id+"'";;
        pst = MySQLConnect.conn.prepareStatement(sql);
        int a = pst.executeUpdate();
        if (a != 0) {
            JOptionPane.showMessageDialog(null, "Success");
            do_attendance h = new do_attendance();
                h.setVisible(true);
                this.dispose();
           
        }
    } catch (Exception e) {
        System.out.println(e.getMessage());
        
    


    }*/
             // TODO add your handling code here:
    }//GEN-LAST:event_txtsubmitActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        Menu obj9=new Menu();
        obj9.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(do_attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(do_attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(do_attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(do_attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new do_attendance().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblstudent;
    private javax.swing.JLabel txtdate;
    private javax.swing.JComboBox<String> txtsemester;
    private javax.swing.JTextField txtstatus;
    private javax.swing.JButton txtsubmit;
    // End of variables declaration//GEN-END:variables
}
