/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package attendance;

/**
 *
 * @author Prem
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtattendance = new javax.swing.JLabel();
        txtattendance1 = new javax.swing.JLabel();
        txtattendance2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtaddstudent = new javax.swing.JLabel();
        txtaddstudent1 = new javax.swing.JLabel();
        txtdoattendance = new javax.swing.JPanel();
        txtaddstudent2 = new javax.swing.JLabel();
        txtaddstudent3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(97, 212, 195));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtattendance2MouseClicked(evt);
            }
        });

        txtattendance.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        txtattendance.setForeground(new java.awt.Color(255, 255, 255));
        txtattendance.setText("Student");
        txtattendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtattendance2MouseClicked(evt);
            }
        });

        txtattendance1.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        txtattendance1.setForeground(new java.awt.Color(255, 255, 255));
        txtattendance1.setText("      Attendance");
        txtattendance1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtattendance2MouseClicked(evt);
            }
        });

        txtattendance2.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        txtattendance2.setForeground(new java.awt.Color(255, 255, 255));
        txtattendance2.setText("Record");
        txtattendance2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtattendance2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtattendance2)
                .addGap(108, 108, 108))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(txtattendance1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 110, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtattendance)
                .addGap(104, 104, 104))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(txtattendance)
                .addGap(68, 68, 68)
                .addComponent(txtattendance1)
                .addGap(42, 42, 42)
                .addComponent(txtattendance2)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(97, 212, 195));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        txtaddstudent.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        txtaddstudent.setForeground(new java.awt.Color(255, 255, 255));
        txtaddstudent.setText("ADD");
        txtaddstudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        txtaddstudent1.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        txtaddstudent1.setForeground(new java.awt.Color(255, 255, 255));
        txtaddstudent1.setText("STUDENT");
        txtaddstudent1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        txtdoattendance.setBackground(new java.awt.Color(97, 212, 195));
        txtdoattendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtdoattendanceMouseClicked(evt);
            }
        });

        txtaddstudent2.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        txtaddstudent2.setForeground(new java.awt.Color(255, 255, 255));
        txtaddstudent2.setText("Today's");
        txtaddstudent2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtaddstudent2jPanel3MouseClicked(evt);
            }
        });

        txtaddstudent3.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        txtaddstudent3.setForeground(new java.awt.Color(255, 255, 255));
        txtaddstudent3.setText("Attendance");
        txtaddstudent3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtaddstudent3jPanel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout txtdoattendanceLayout = new javax.swing.GroupLayout(txtdoattendance);
        txtdoattendance.setLayout(txtdoattendanceLayout);
        txtdoattendanceLayout.setHorizontalGroup(
            txtdoattendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtdoattendanceLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(txtdoattendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtaddstudent2)
                    .addComponent(txtaddstudent3))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        txtdoattendanceLayout.setVerticalGroup(
            txtdoattendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtdoattendanceLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txtaddstudent2)
                .addGap(25, 25, 25)
                .addComponent(txtaddstudent3)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtaddstudent)
                            .addComponent(txtaddstudent1)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtdoattendance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txtaddstudent)
                .addGap(25, 25, 25)
                .addComponent(txtaddstudent1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(txtdoattendance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
Add_Student obj2=new Add_Student();
obj2.setVisible(true);
this.dispose();
        
// TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseClicked

    private void txtattendance2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtattendance2MouseClicked
        view obj3=new view();
        obj3.setVisible(true);
        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_txtattendance2MouseClicked

    private void txtaddstudent2jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtaddstudent2jPanel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddstudent2jPanel3MouseClicked

    private void txtaddstudent3jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtaddstudent3jPanel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddstudent3jPanel3MouseClicked

    private void txtdoattendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdoattendanceMouseClicked
        do_attendance obj4=new do_attendance();
obj4.setVisible(true);
this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_txtdoattendanceMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel txtaddstudent;
    private javax.swing.JLabel txtaddstudent1;
    private javax.swing.JLabel txtaddstudent2;
    private javax.swing.JLabel txtaddstudent3;
    private javax.swing.JLabel txtattendance;
    private javax.swing.JLabel txtattendance1;
    private javax.swing.JLabel txtattendance2;
    private javax.swing.JPanel txtdoattendance;
    // End of variables declaration//GEN-END:variables
}
